apiVersion: v2
name: kaspr-resources
description: A Helm chart for deploying Kaspr custom resources to Kubernetes.

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart, its templates or underlying CRDs.
version: 2.1.0